### ISSUE TITLE
Check out libusbx

### ISSUE THREAD

**Issue by IguanaBen** [iguanaworks/iguanair#12]
**Reported by jdunn on 5 Feb 2013 02:22 UTC**
Currently libusb post version 1.0 works fine for our purposes, but for more advanced USB devices a fork of libusb has been made called libusbx.  We should add a new driver if there is any benefit in linking directly to libusbx, however, they provide a drop-in replacement for the libusb 1.0 line so I believe it is technically unnecessary for the time being.

**Comment by jdunn14** [comment]
When I checked long ago libusbx and libusb had different header files, but now, from the libusbx RPM:

> Libusbx is a fork of the original libusb, which is a fully API and ABI
> compatible drop in for the libusb-1.0.9 release. The libusbx fork was
> started by most of the libusb-1.0 developers, after the original libusb
> project did not produce a new release for over 18 months.

The libusbx-devel package also provides a libusb.h, not a libusbx.h, so our current libusb driver is already using the right API.  Closing this.
