### ISSUE TITLE
Variable overlap

### ISSUE THREAD

**Issue by IguanaBen** [iguanaworks/iguanair#18]
**Reported by jdunn on 26 Oct 2014 03:10 UTC**
While implementing --resend in the firmware I figured out that tmp4 and last_pulse actually overlap with the first two bytes of the control_pkt buffer.  This is bad, but not causing us any problems right now.  I believe fixing this would require a new loader so I will put this off until we need a new loader (0x0400) for some other reason.

**Comment by jdunn14** [comment]
I cannot really see us fixing this on the current hardware.  If we switch to a new chip at some point then this won't be a problem.  Closing this as basically "won't fix".
