### ISSUE TITLE
Please update  build information

### ISSUE THREAD

**Issue by leamas** [iguanaworks/iguanair#19]
The information on http://www.iguanaworks.net/support/ is partly outdated. It's about Fedora specifics (plain bugs), the Ubuntu debian situation and the upcoming lirc plugin system.

Too dumb to create a merge request for the wiki, but an ordered  set of three patches are available at http://ur1.ca/k9z9l, http://ur1.ca/k9z9o and http://ur1.ca/k9z9q .

**Comment by jdunn14** [comment]
Sooo, this appears to be ancient and all the paste links are broken.  I'm going to go ahead and close this, but please open a new ticket if any of this still applies, and I apologize for *completely* dropping this one the floor.  My fault entirely.
