### ISSUE TITLE
No systemd support.

### ISSUE THREAD

**Issue by leamas** [iguanaworks/iguanair#29]
Effectively, all linux:es have moved to systemd. Adding systemd support is trivial, and doesn't hurt if system uses traditional sysV.

Attaching  /lib/systemd/system/iguanair,service and  usr/lib/tmpfiles.d/iguanair.conf form the fedora package. They should be fine upstream, one of the ideas with systemd is that all distributions shares these files. txt-suffuixes as required by github...

Remaining  issue is to configure  80-iguanaIR.rules so that it doesn't duplicate creation of the temprary directory on a systemd installation.

[iguanaIR.service.txt](https://github.com/iguanaworks/iguanair/files/736307/iguanaIR.service.txt)
[iguanair.conf.txt](https://github.com/iguanaworks/iguanair/files/736309/iguanair.conf.txt)

**Comment by jdunn14** [comment]
Should be fixed by the merge of #28

**Comment by leamas** [comment]
Indeed, closing
