### ISSUE TITLE
firmware files are missing

### ISSUE THREAD

**Issue by leamas** [iguanaworks/iguanair#30]
After running a *make install* the firmware .hex files are missing the in the installation directory; these do exist in the current 1.1.0 distribution.

Part of the problem is that the source dir *files/python/usr/share/iguanaIR-reflasher/hex/* seems empty

**Comment by jdunn14** [comment]
This should be resolved by fb6ebd12b1bb54dfd6000539a220f850cdb5186c.

**Comment by leamas** [comment]
Closing to get it away from my table - trusting you to test it :)
