### ISSUE TITLE
Iguana Works still activ

### ISSUE THREAD

**Issue by 2richardt** [iguanaworks/iguanair#51]
Is Iquana Works still active?  I placed an order but dates for the support tickets are 2 years old. Can I expect delivery?

**Comment by IguanaBen** [comment]
Yes, Iguanaworks is still active. You should have received a confirmation e-mail after your order was placed. We have received your order and it should ship out on Monday. 

Thank you for your business.

**Comment by 2richardt** [comment]
Ben,
Great, thanks.  I see the confirmation now.
Best regards,
Richard Thompson
818-264-8656
