### ISSUE TITLE
remove stopped or removed flag in usbclient.c

### ISSUE THREAD

**Issue by IguanaBen** [iguanaworks/iguanair#6]
**Reported by jdunn on 23 Jun 2009 02:36 UTC**
After the addition of the stopped flag to the usb client objects the functionality of the stopped flag is at least partially duplicated.  Most likely we can get away with a single flag.  Actually I'm sure we can.  The worker thread wrapper should do the freeing of the usb.  In any case, this works alright for now, and will be fixed in a later patch.

**Comment by jdunn14** [comment]
I'm not even sure what this means and I wrote it originally.  Of course it was like 8 years ago....
